package org.example;/* Generated By:JavaCC: Do not edit this line. CleaningLangConstants.java Version 8.0.0 */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CleaningLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WASH = 5;
  /** RegularExpression Id. */
  int SWEEP = 6;
  /** RegularExpression Id. */
  int MOP = 7;
  /** RegularExpression Id. */
  int VACUUM = 8;
  /** RegularExpression Id. */
  int STRAIGHTEN = 9;
  /** RegularExpression Id. */
  int THE = 10;
  /** RegularExpression Id. */
  int DISHES = 11;
  /** RegularExpression Id. */
  int LAUNDRY = 12;
  /** RegularExpression Id. */
  int BATHROOMS = 13;
  /** RegularExpression Id. */
  int FLOOR = 14;
  /** RegularExpression Id. */
  int PAPERS = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Wash\"",
    "\"Sweep\"",
    "\"Mop\"",
    "\"Vacuum\"",
    "\"Straighten\"",
    "\"the\"",
    "\"dishes\"",
    "\"laundry\"",
    "\"bathrooms\"",
    "\"floor\"",
    "\"papers\"",
    "\".\"",
  };
}
/* JavaCC - OriginalChecksum=9a6b410dee4e97536a545590430d0090 (do not edit this line) */
